### ISSUE TITLE
Invalid Memory use when trying to Upgrade or use fresh Install of Mattermost

### ISSUE THREAD

**Issue by forelabs** [mattermost/platform#1833]
Hi,

I wanted to uprade mattermost to a newer version (from 1.1.0 to 1.1.1) - but I get this error message:

```
http: panic serving 192.168.0.20:52106: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
html/template.(*Template).lookupAndEscapeTemplate(0x0, 0xb8ad10, 0xb, 0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:99 +0x72
html/template.(*Template).ExecuteTemplate(0x0, 0x7f3b6f70aa10, 0xc2082321e0, 0xb8ad10, 0xb, 0xa4ef40, 0xc2082b0fe0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:88 +0x54
github.com/mattermost/platform/web.(*HtmlTemplatePage).Render(0xc2082b0fe0, 0xc2082a4000, 0x7f3b6f70a960, 0xc2082321e0)
	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:39 +0xb9
github.com/mattermost/platform/web.root(0xc2082a4000, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/home/travis/gopath/src/github.com/mattermost/platform/web/web.go:150 +0x256
github.com/mattermost/platform/api.handler.ServeHTTP(0xcbdbf0, 0x100000000, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/home/travis/gopath/src/github.com/mattermost/platform/api/context.go:177 +0x1234
github.com/mattermost/platform/api.(*handler).ServeHTTP(0xc20817ecc0, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	<autogenerated>:1 +0xbd
github.com/gorilla/mux.(*Router).ServeHTTP(0xc20819f270, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/throttled/throttled.func·003(0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/home/travis/gopath/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/throttled/throttled/throttler.go:64 +0x15b
net/http.HandlerFunc.ServeHTTP(0xc20828a860, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc208067078, 0x7f3b6f70a960, 0xc2082321e0, 0xc2083104e0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2082320a0)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

```

Why do I get **invalid memory address or nil pointer** ?

I also get this error when trying to use a fresh installation of mattermost.

**Comment by forelabs** [comment]
Seems to work after restart server - sorry for opening an issue
