### ISSUE TITLE
mattermost.service directly goes into failed state

### ISSUE THREAD

**Issue by cambiph** [mattermost/platform#1953]
Hey guys,

I am having quite some trouble with having mattermost start automatically via systemd.
I am running mattermost on RHEL 7 and I followed the guide step by step (skipped the nginx step because there is no need for that now).
I can run mattermost via /opt/mattermost/bin/platform without issues but when I try
```
sudo systemctl start mattermost
```
The service doesn't seem to start and 
```
sudo systemctl status mattermost
```
returns
```
mattermost.service - Mattermost
   Loaded: loaded (/etc/systemd/system/mattermost.service; enabled)
   Active: failed (Result: exit-code) since Fri 2016-01-22 13:17:13 CET; 6s ago
  Process: 8635 ExecStart=/opt/mattermost/bin/platform (code=exited, status=2)
 Main PID: 8635 (code=exited, status=2)

platform[8635]: /usr/local/go/src/os/signal/signal_unix.go:20
platform[8635]: created by os/signal.init.1
platform[8635]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
platform[8635]: goroutine 6 [runnable]:
platform[8635]: code.google.com/p/log4go.ConsoleLogWriter.run(0xc820014180, 0x7f3212ad81e8, 0xc820022010)
platform[8635]: /go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:23
platform[8635]: created by code.google.com/p/log4go.NewConsoleLogWriter
platform[8635]: /go/src/github.com/mattermost/platform/Godeps/_workspace/src/code.google.com/p/log4go/termlog.go:19 +0x6e
systemd[1]: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: Unit mattermost.service entered failed state.
```

If you need additional info, please ask, not sure if this is sufficient.
Thank you in advance!

Regards

**Comment by cambiph** [comment]
Ok, the problem has been solved.
I accidentally started mattermost once with another user.
A logfile was created /opt/mattermost/logs/mattermost.log with that user.
Systemd starts the service as mattermost user and cannot write to the logfile, resulting in a failure state.
