### ISSUE TITLE
Gitlab omnibus 8.5.0: can make mattermost work

### ISSUE THREAD

**Issue by agend** [mattermost/platform#2226]
Waited for 8.5.0 release so it will solve issue:
```
[2016/02/23 18:18:32 MSK] [CRIT] The database schema version of 1.2.1 cannot be upgraded.  You must not skip a version.
```

But no luck.

And tried to check mattermost version no luck as well:
```
/opt/gitlab/embedded/bin/mattermost -version
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6194e1]

goroutine 1 [running]:
github.com/mattermost/platform/utils.LoadConfig(0xcc72d0, 0xb)
        /go/src/github.com/mattermost/platform/utils/config.go:144 +0x2d1
main.main()
        /go/src/github.com/mattermost/platform/mattermost.go:54 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc82000a600, 0x7ffe2cf831e8, 0xc82002a010)
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:33 +0x69
created by github.com/alecthomas/log4go.NewConsoleLogWriter
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5
```

**Comment by cmtonkinson** [comment]
After the update this morning (gitlab-omnibus 8.5.0) I get a 502 on Mattermost and this spams the log every second:

```
2016-02-23_16:12:29.30087 panic: runtime error: invalid memory address or nil pointer dereference
2016-02-23_16:12:29.30095 [signal 0xb code=0x1 addr=0x0 pc=0x62099f]
2016-02-23_16:12:29.30101 
2016-02-23_16:12:29.30103 goroutine 1 [running]:
2016-02-23_16:12:29.30108 github.com/mattermost/platform/utils.TestConnection(0xc820135400)
2016-02-23_16:12:29.30111 	/go/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
2016-02-23_16:12:29.30117 github.com/mattermost/platform/utils.LoadConfig(0x7ffdd7813ee5, 0x26)
2016-02-23_16:12:29.30122 	/go/src/github.com/mattermost/platform/utils/config.go:171 +0xdbe
2016-02-23_16:12:29.30127 main.main()
2016-02-23_16:12:29.30129 	/go/src/github.com/mattermost/platform/mattermost.go:54 +0x43
2016-02-23_16:12:29.30137 
2016-02-23_16:12:29.30139 goroutine 17 [syscall, locked to thread]:
2016-02-23_16:12:29.30143 runtime.goexit()
2016-02-23_16:12:29.30146 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
2016-02-23_16:12:29.30151 
2016-02-23_16:12:29.30152 goroutine 5 [syscall]:
2016-02-23_16:12:29.30156 os/signal.loop()
2016-02-23_16:12:29.30159 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
2016-02-23_16:12:29.30165 created by os/signal.init.1
2016-02-23_16:12:29.30167 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
2016-02-23_16:12:29.30172 
2016-02-23_16:12:29.30174 goroutine 18 [select]:
2016-02-23_16:12:29.30178 github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc8201e6000)
2016-02-23_16:12:29.30182 	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:87 +0xabc
2016-02-23_16:12:29.30187 created by github.com/alecthomas/log4go.NewFileLogWriter
2016-02-23_16:12:29.30190 	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b
```

I don't know if this is a Mattermost-specific problem or something in CE/Omnibus. Cross-posted to https://gitlab.com/gitlab-org/gitlab-mattermost/issues/60

**Comment by it33** [comment]
@agend, Mattermost in GitLab 8.5 can upgrade from GitLab 8.4 or GitLab 8.3 (2 versions), but not from GitLab 8.2. You'd need to upgrade from 8.2 to 8.3 before upgrading to 8.5.

Please see http://doc.gitlab.com/omnibus/gitlab-mattermost/

**Comment by cmtonkinson** [comment]
I upgraded from 8.4.4, which was a fresh install.

**Comment by bkaestner** [comment]
I can't find the resource anymore, but I fixed it with the following steps yesterday. They should probably work for you too, @agend. First, stop GitLab's mattermost:

``` sh
$ gitlab-ctl stop mattermost
```
Next, download all versions of mattermost that are greater than your current one and cannot get automatically upgraded from GitLab's mattermost (e.g. up to V-3) from [the release page](https://github.com/mattermost/platform/releases).

In order of ascending versions, due the following:

``` sh
$ cd /tmp
$ wget https://github.com/mattermost/platform/releases/download/VERSION/mattermost.tar.gz
$ tar xf mattermost*
$ cd mattermost/bin
$ cp /var/opt/gitlab/mattermost/config.json ../config/
$ timeout 10s ./plattform
```

This will migrate your mattermost data step by step. Afterwards, you can enable GitLab's mattermost again.

**Comment by cmtonkinson** [comment]
Looks like my stack trace is different and this thread is more about upgrading than anything else. I'll open a separate ticket for mine.

**Comment by agend** [comment]
@bkaestner Thank you, I will try it later.

**Comment by agend** [comment]
@bkaestner worked like a charm - thanks a lot!

**Comment by artooro** [comment]
The steps from @bkaestner did not work for me. I have the same issue as @agend 

Except when I run "timeout 10s ./platform" I get the following output.
Also running 8.5 and I run the upgrade with every release.

```
timeout 10s ./platform 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x62099f]

goroutine 1 [running]:
github.com/mattermost/platform/utils.TestConnection(0xc820129400)
        /go/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
github.com/mattermost/platform/utils.LoadConfig(0xc8200cb620, 0x22)
        /go/src/github.com/mattermost/platform/utils/config.go:171 +0xdbe
main.main()
        /go/src/github.com/mattermost/platform/mattermost.go:54 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [runnable]:
github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc8201ca280)
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:78
created by github.com/alecthomas/log4go.NewFileLogWriter
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b
```

And running `/opt/gitlab/embedded/bin/mattermost -version`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x62099f]

goroutine 1 [running]:
github.com/mattermost/platform/utils.TestConnection(0xc820127400)
        /go/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
github.com/mattermost/platform/utils.LoadConfig(0xc8200c9680, 0x22)
        /go/src/github.com/mattermost/platform/utils/config.go:171 +0xdbe
main.main()
        /go/src/github.com/mattermost/platform/mattermost.go:54 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [runnable]:
github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc820129ea0)
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:78
created by github.com/alecthomas/log4go.NewFileLogWriter
        /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b
```

**Comment by agend** [comment]
@artooro What path you are running it from? It seems that problem with access to config file. Version isn't working for me as well

**Comment by artooro** [comment]
I tried running it from both /tmp/mattermost/bin  and from other paths as well.

**Comment by agend** [comment]
@artooro What user do you use to run ut?

**Comment by artooro** [comment]
@agend I was running at the root user.

**Comment by agend** [comment]
@artooro try run as mattermost

**Comment by artooro** [comment]
@agend it seems it was something in gitlab.rb one of my config options was causing this. I deleted all the mattermost config lines except for the external_url and ssl_certificate/_key options and now it's running.
I'll have to add them all back in one at a time and see which one caused this.
