### ISSUE TITLE
Crash every second

### ISSUE THREAD

**Issue by cmtonkinson** [mattermost/platform#2238]
After the update to gitlab-omnibus `8.5.0` (from `8.4.4`) I get a `502` on the Mattermost page and this stack trace spams the log every second:

2016-02-23_16:12:29.30087 panic: runtime error: invalid memory address or nil pointer dereference
2016-02-23_16:12:29.30095 [signal 0xb code=0x1 addr=0x0 pc=0x62099f]
2016-02-23_16:12:29.30101 
2016-02-23_16:12:29.30103 goroutine 1 [running]:
2016-02-23_16:12:29.30108 github.com/mattermost/platform/utils.TestConnection(0xc820135400)
2016-02-23_16:12:29.30111   /go/src/github.com/mattermost/platform/utils/mail.go:82 +0x9f
2016-02-23_16:12:29.30117 github.com/mattermost/platform/utils.LoadConfig(0x7ffdd7813ee5, 0x26)
2016-02-23_16:12:29.30122   /go/src/github.com/mattermost/platform/utils/config.go:171 +0xdbe
2016-02-23_16:12:29.30127 main.main()
2016-02-23_16:12:29.30129   /go/src/github.com/mattermost/platform/mattermost.go:54 +0x43
2016-02-23_16:12:29.30137 
2016-02-23_16:12:29.30139 goroutine 17 [syscall, locked to thread]:
2016-02-23_16:12:29.30143 runtime.goexit()
2016-02-23_16:12:29.30146   /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
2016-02-23_16:12:29.30151 
2016-02-23_16:12:29.30152 goroutine 5 [syscall]:
2016-02-23_16:12:29.30156 os/signal.loop()
2016-02-23_16:12:29.30159   /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
2016-02-23_16:12:29.30165 created by os/signal.init.1
2016-02-23_16:12:29.30167   /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
2016-02-23_16:12:29.30172 
2016-02-23_16:12:29.30174 goroutine 18 [select]:
2016-02-23_16:12:29.30178 github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc8201e6000)
2016-02-23_16:12:29.30182   /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:87 +0xabc
2016-02-23_16:12:29.30187 created by github.com/alecthomas/log4go.NewFileLogWriter
2016-02-23_16:12:29.30190   /go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b

I don't know if this is a Mattermost-specific problem or something in CE/Omnibus. Cross-posted to https://gitlab.com/gitlab-org/gitlab-mattermost/issues/60

**Comment by coreyhulen** [comment]
Hi @cmtonkinson it appears the system is crashing because it's trying to test the mail settings and the localized strings aren't loaded yet.  https://github.com/mattermost/platform/pull/2241 will fix this issue.  You can work around this issue by disabling sending of notifications temporarily and re-enabling via the system console once mattermost is running.  You can do this by modifying config.json and setting
```
"EmailSettings": {
        "SendEmailNotifications": false,
```

Then you can re-enable it from the system console.  You also might want to test the connection from the system console because it appears your email settings are not configured properly.

**Comment by cmtonkinson** [comment]
Thanks @coreyhulen, your workaround did succeed. In my case (installed via gitlab-omnibus) the workaround was to modify `/etc/gitlab/gitlab.rb`:

    - mattermost['email_send_email_notifications'] = true
    + mattermost['email_send_email_notifications'] = false

since the Mattermost config.json is managed by the main GitLab config via Chef.

Also, your suspicion was right - the email configuration isn't (has never been) correct.
