### ISSUE TITLE
Debian Jessie Panic: invalid memory address.

### ISSUE THREAD

**Issue by karlbateman** [mattermost/platform#2308]
Help!

I get to section 7. Run the MatterMost server by typing `./platform` and I get the following.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6198b0]

goroutine 1 [running]:
github.com/mattermost/platform/utils.LoadConfig(0xc8200cb680, 0x22)
	/go/src/github.com/mattermost/platform/utils/config.go:152 +0x6a0
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:54 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [runnable]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc82000e600, 0x7f7a5392f1e8, 0xc820026010)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:32
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5
```
I am running Debian Jessie amd64 with Mattermost 2.0.0 :smile:

**Comment by enahum** [comment]
Can you try to run ./platform with the -config flag?

**Comment by coreyhulen** [comment]
My guess is your config.json isn't well formed or is missing.  You might try something like https://jsonformatter.curiousconcept.com/ to see if it's valid.

**Comment by karlbateman** [comment]
Hi @enahum,
Thanks for getting back to me, so for the late reply. Running the command `./platform -config="/opt/mattermost/config/config.json"` produces the following.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6198b0]

goroutine 1 [running]:
github.com/mattermost/platform/utils.LoadConfig(0x7fff25c76691, 0x22)
	/go/src/github.com/mattermost/platform/utils/config.go:152 +0x6a0
main.main()
	/go/src/github.com/mattermost/platform/mattermost.go:54 +0x43

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [runnable]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc82000a6e0, 0x7f45c3a871e8, 0xc820028010)
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:32
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5
```

@coreyhulen you seem to have found something with your suggestion. I had an issue with a missing `,` so when I get a change, I will re-run and update this with my results. Thanks again :smile:

**Comment by karlbateman** [comment]
It's fixed so thank you both for your support :+1:

**Comment by brunodegoyrans** [comment]
Hi

I had the same issue. In my case, it was the SMTP password that was wrong. So this issue may happen if a parameter is false. Not only a question of misformated json.

**Comment by brunodegoyrans** [comment]
Also, In the desktop app, I had a "in progress" icon right after all my sent messages, although the messages were correctly sent and received by other users. 
Since I gave the right smtp password in the json, the icon does not show anymore.
