### ISSUE TITLE
android application not working with 2.1 - not a mattermost server

### ISSUE THREAD

**Issue by vcazan** [mattermost/platform#2439]
I've compiled the apk from master of android repo, it runs fine but when I try and use my team url it gives me the message "This address does not appear to be a Mattermost server"

I can log into the testing server fine but not my server at https://team.arblabs.com

Does anyone know what could be causing this?

**Comment by vcazan** [comment]
Also get this error in console:
`03-15 14:09:48.994 2295-2375/com.mattermost.mattermost E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb40931f0
03-15 14:09:49.012 2295-2295/com.mattermost.mattermost E/Error: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
                                                                    at com.squareup.okhttp.Connection.connectTls(Connection.java:235)
                                                                    at com.squareup.okhttp.Connection.connectSocket(Connection.java:199)
                                                                    at com.squareup.okhttp.Connection.connect(Connection.java:172)
                                                                    at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                    at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
                                                                    at com.squareup.okhttp.Call.getResponse(Call.java:267)
                                                                    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
                                                                    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
                                                                    at com.squareup.okhttp.Call.access$100(Call.java:34)
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                 Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
                                                                    at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
                                                                    at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
                                                                    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                    at com.squareup.okhttp.Connection.connectTls(Connection.java:235) 
                                                                    at com.squareup.okhttp.Connection.connectSocket(Connection.java:199) 
                                                                    at com.squareup.okhttp.Connection.connect(Connection.java:172) 
                                                                    at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
                                                                    at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) 
                                                                    at com.squareup.okhttp.Call.getResponse(Call.java:267) 
                                                                    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) 
                                                                    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) 
                                                                    at com.squareup.okhttp.Call.access$100(Call.java:34) 
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162) 
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                    at java.lang.Thread.run(Thread.java:818) 
                                                                 Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) 
                                                                    at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) 
                                                                    at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556) 
                                                                    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                                    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324) 
                                                                    at com.squareup.okhttp.Connection.connectTls(Connection.java:235) 
                                                                    at com.squareup.okhttp.Connection.connectSocket(Connection.java:199) 
                                                                    at com.squareup.okhttp.Connection.connect(Connection.java:172) 
                                                                    at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367) 
                                                                    at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328) 
                                                                    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245) 
                                                                    at com.squareup.okhttp.Call.getResponse(Call.java:267) 
                                                                    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224) 
                                                                    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195) 
                                                                    at com.squareup.okhttp.Call.access$100(Call.java:34) 
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162) 
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                    at java.lang.Thread.run(Thread.java:818) `

**Comment by it33** [comment]
Try entering `example.com/teamname`? 

The error message could be more clear: https://github.com/mattermost/android/pull/7/files

**Comment by vcazan** [comment]
I tried without the https and got the same error

**Comment by lfbrock** [comment]
Hi @vcazan, 

I think what he meant was adding the team name to the end of your URL, it would need to be https://team.arblabs.com/teamname. 

The app currently doesn't connect to the root page, it needs the URL for the team page.

**Comment by vcazan** [comment]
Thanks I have tried that http://team.arblabs.com/main and it still
![capture](https://cloud.githubusercontent.com/assets/324461/13825440/f9c3823c-eb88-11e5-87f9-b0d3e0420c07.PNG)
 giving me the same error

**Comment by lfbrock** [comment]
Hmm not sure what is going on then, would you be able to move this over to the troubleshooting forum (see instructions above) and see if anyone else has had similar issues?

**Comment by lfbrock** [comment]
Does your Mattermost server have a self signed certificate? If so, I think that's why it won't connect - we have a ticket here to look into the issue (ticket is for iOS, but it's a problem for Android as well): https://mattermost.atlassian.net/browse/PLT-2169

**Comment by vcazan** [comment]
@lfbrock Yes it does and it is valid

https://team.arblabs.com/main

**Comment by lfbrock** [comment]
Alright sorry I'm not sure then, can you copy this over to https://forum.mattermost.org/ to see if anyone else has hit this issue?

**Comment by nicolas-raoul** [comment]
Many people have the same problem, please reopen thanks!
See http://forum.mattermost.org/t/android-app-connect-to-mattermost-team-link/1417

By the way I have this problem on a non-SSL server, so it is not about certificates.

Android app: Mattermost 3.0.6  
Server: Mattermost Team Edition 2.2.0

![screenshot_20160525-152822](https://cloud.githubusercontent.com/assets/99590/15530230/24a2ba68-228e-11e6-87ba-82aacaee6711.png)
The same URL works well in web browser.

**Comment by SacDin** [comment]
+1

**Comment by it33** [comment]
Hi everyone, 

Please note [that the hosted Mattermost mobile apps on iTunes and Google Play are for Mattermost 3.0 and higher.](https://forum.mattermost.org/t/new-3-0-android-and-ios-apps-pushed-to-google-play-and-itunes/1542), and support multi-team accounts. 

If you're still on a Mattermost 2.x server without multi-team account support, you would need to either upgrade your server to 3.0 or compile the 2.x mobile apps from their open source repos. 

The "The address does not appear to be a Mattermost server" sounds like an error message with using the 3.0 mobile apps with the wrong version server. 

The Android error message is not as clear as the iOS one (which talks about incompatible versions), and [here's a PR to fix that for Android.](https://github.com/mattermost/android/pull/21/files).

**Comment by SacDin** [comment]
How do I know the version of my mattermost server ? I'm running
pre-included version in Gitlab 8.x.

On Sun, May 29, 2016 at 12:06 AM, it33 <notifications@github.com> wrote:

> Hi everyone,
>
> Please note that the hosted Mattermost mobile apps on iTunes and Google
> Play are for Mattermost 3.0 and higher.
> <https://forum.mattermost.org/t/new-3-0-android-and-ios-apps-pushed-to-google-play-and-itunes/1542>,
> and support multi-team accounts.
>
> If you're still on a Mattermost 2.x server without multi-team account
> support, you would need to either upgrade your server to 3.0 or compile the
> 2.x mobile apps from their open source repos.
>
> The "The address does not appear to be a Mattermost server" sounds like an
> error message with using the 3.0 mobile apps with the wrong version server.
>
> The Android error message is not as clear as the iOS one (which talks
> about incompatible versions), and here's a PR to fix that for Android.
> <https://github.com/mattermost/android/pull/21/files>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/platform/issues/2439#issuecomment-222323070>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFsf4RXUNUxTSCB0bsSRWLPiw4HFEZgpks5qGIsagaJpZM4HxTHp>
> .
>



-- 
Regards,
Sachin Dindor
SacDin Enterprise Pvt Ltd

**Comment by SacDin** [comment]
How do I know the version of my mattermost server ? I'm running pre-included version in Gitlab 8.x.

**Comment by sheepherd** [comment]
I'd like to report the same Issue.
Android App Version: 3.0.6
Mattermost Server Version: 3.0.3
The Mattermost server works flawlessly, but when connecting with the Android App I also get "The address does not appear to be a Mattermost server".
The request arrives at port 443 on the server but apparently nginx does not receive a valid http request, since it does not log anything.
I can provide more Information if needed.

08:41:51.549168 IP (tos 0x0, ttl 64, id 26956, offset 0, flags [DF], proto TCP (6), length 239) 
    10.1.5.108.38857 > 10.1.2.23.443: Flags [P.], cksum 0xe228 (correct), seq 1715497096:1715497283, ack 2926661490, win 343, options [nop,nop,TS val 59834830 ecr 37875980], length 187 
	0x0000:  4500 00ef 694c 4000 4006 b538 0a01 056c  E...iL@.@..8...l 
	0x0010:  0a01 0217 97c9 01bb 6640 6888 ae71 4f72  ........f@h..qOr 
	0x0020:  8018 0157 e228 0000 0101 080a 0391 01ce  ...W.(.......... 
	0x0030:  0241 f10c 1603 0100 b601 0000 b203 032d  .A.............- 
	0x0040:  50eb 7942 6110 fedd c243 7163 5478 06e5  P.yBa....CqcTx.. 
	0x0050:  e874 a249 c00f 378f 48b5 ddd9 1f69 8500  .t.I..7.H....i.. 
	0x0060:  001a c02b c02f 009e c00a c009 c013 c014  ...+./.......... 
	0x0070:  0033 0039 009c 002f 0035 00ff 0100 006f  .3.9.../.5.....o 
	0x0080:  0000 001c 001a 0000 1763 6861 742e 6164  .........XXX.XX 
	0x0090:  6669 6e69 732d 7379 6772 6f75 702e 6368  SERVERXX.XX 
	0x00a0:  0017 0000 0023 0000 000d 0016 0014 0601  .....#.......... 
	0x00b0:  0603 0501 0503 0401 0403 0301 0303 0201  ................ 
	0x00c0:  0203 0010 0017 0015 0268 3208 7370 6479  .........h2.spdy 
	0x00d0:  2f33 2e31 0868 7474 702f 312e 3100 0b00  /3.1.http/1.1... 
	0x00e0:  0201 0000 0a00 0800 0600 1700 1800 19    ...............

**Comment by raphael0202** [comment]
Hello everyone. I have the same problem, with a fresh install using docker (mattermost server 3.1.0), and the last version of mattermost app (v3.0.6) and I'm using a SSL certificate from let's encrypt.

**Comment by lfbrock** [comment]
Hi @raphael0202, can you check the troubleshooting forums to see if any related posts there help? (For example, maybe [this one](https://forum.mattermost.org/t/android-app-connect-to-mattermost-team-link/1417/13))

If there's nothing there, you can start a new thread on the issue.
