### ISSUE TITLE
runtime error after upgrade to mattermost 2.1

### ISSUE THREAD

**Issue by williamwu0220** [mattermost/platform#2485]
After upgrading to mattermost 2.1, I noticed errors as follows:

```
[2016/03/20 05:12:50 EDT] [DEBG] /api/v1/users/profiles
[2016/03/20 05:12:53 EDT] [DEBG] /api/v1/users/status
[2016/03/20 05:12:53 EDT] [DEBG] /api/v1/channels/7sw1pg6qafgnm8eo8x93bgjw5w/create
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xf0 pc=0x5b0b57]

goroutine 407 [running]:
panic(0xc5e740, 0xc82000a0e0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/mattermost/platform/api.sendNotifications(0xc820677c20, 0xc82068e620, 0xc820591c20, 0xc820491d90, 0xc8202439c0, 0xc8200e0c00, 0xb, 0x10)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/post.go:487 +0x5f67
created by github.com/mattermost/platform/api.handlePostEventsAndForget.func1
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/post.go:271 +0xe02
```

I've tried to turn off all the notification settings, but the errors still be there.

environment:
Mattermost: 2.1 pre-compiled binary
OS: Debian Jessie x64

**Comment by williamwu0220** [comment]
Relevent config settings are as follows (sentitive parts are masked):

```json
{
    "ServiceSettings": {
        "ListenAddress": ":8065",
        "MaximumLoginAttempts": 10,
        "SegmentDeveloperKey": "",
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": true,
        "EnableOutgoingWebhooks": true,
        "EnableCommands": true,
        "EnableOnlyAdminIntegrations": true,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "EnableTesting": false,
        "EnableDeveloper": false,
        "EnableSecurityFixAlert": true,
        "EnableInsecureOutgoingConnections": false,
        "AllowCorsFrom": "",
        "SessionLengthWebInDays": 30,
        "SessionLengthMobileInDays": 30,
        "SessionLengthSSOInDays": 30,
        "SessionCacheInMinutes": 10,
        "WebsocketSecurePort": 443,
        "WebsocketPort": 80
    },
    "TeamSettings": {
        "SiteName": "xxxxxxxxxxxxxxxxxxxx",
        "MaxUsersPerTeam": 500,
        "EnableTeamCreation": false,
        "EnableUserCreation": true,
        "RestrictCreationToDomains": "",
        "RestrictTeamNames": true,
        "EnableTeamListing": true
    },
    "SqlSettings": {
        "DriverName": "mysql",
        "DataSource": "xxxxxxxxxxxxxxxxxxxx",
        "DataSourceReplicas": [],
        "MaxIdleConns": 10,
        "MaxOpenConns": 10,
        "Trace": false,
        "AtRestEncryptKey": "xxxxxxxxxxxxxxxxxxxx"
    },
    "LogSettings": {
        "EnableConsole": true,
        "ConsoleLevel": "DEBUG",
        "EnableFile": true,
        "FileLevel": "INFO",
        "FileFormat": "",
        "FileLocation": ""
    },
    "FileSettings": {
        "DriverName": "local",
        "Directory": "./data/",
        "EnablePublicLink": true,
        "PublicLinkSalt": "xxxxxxxxxxxxxxxxxxxx",
        "ThumbnailWidth": 120,
        "ThumbnailHeight": 100,
        "PreviewWidth": 1024,
        "PreviewHeight": 0,
        "ProfileWidth": 128,
        "ProfileHeight": 128,
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "",
        "AmazonS3SecretAccessKey": "",
        "AmazonS3Bucket": "",
        "AmazonS3Region": "",
        "AmazonS3Endpoint": "",
        "AmazonS3BucketEndpoint": "",
        "AmazonS3LocationConstraint": false,
        "AmazonS3LowercaseBucket": false
    },
    "EmailSettings": {
        "EnableSignUpWithEmail": true,
        "EnableSignInWithEmail": true,
        "EnableSignInWithUsername": false,
        "SendEmailNotifications": false,
        "RequireEmailVerification": false,
        "FeedbackName": "",
        "FeedbackEmail": "",
        "SMTPUsername": "",
        "SMTPPassword": "",
        "SMTPServer": "",
        "SMTPPort": "",
        "ConnectionSecurity": "",
        "InviteSalt": "xxxxxxxxxxxxxxxxxxxx",
        "PasswordResetSalt": "xxxxxxxxxxxxxxxxxxxx",
        "SendPushNotifications": false,
        "PushNotificationServer": ""
    },
    "RateLimitSettings": {
        "EnableRateLimiter": true,
        "PerSec": 10,
        "MemoryStoreSize": 10000,
        "VaryByRemoteAddr": true,
        "VaryByHeader": ""
    },
    "PrivacySettings": {
        "ShowEmailAddress": false,
        "ShowFullName": true
    },
    "SupportSettings": {
        "TermsOfServiceLink": "/static/help/terms.html",
        "PrivacyPolicyLink": "/static/help/privacy.html",
        "AboutLink": "/static/help/about.html",
        "HelpLink": "/static/help/help.html",
        "ReportAProblemLink": "/static/help/report_problem.html",
        "SupportEmail": "feedback@mattermost.com"
    },
    "GitLabSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
    "GoogleSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
    "LdapSettings": {
        "Enable": false,
        "LdapServer": null,
        "LdapPort": 389,
        "BaseDN": null,
        "BindUsername": null,
        "BindPassword": null,
        "FirstNameAttribute": null,
        "LastNameAttribute": null,
        "EmailAttribute": null,
        "UsernameAttribute": null,
        "IdAttribute": null,
        "QueryTimeout": 60
    }
}
```

**Comment by williamwu0220** [comment]
Sorry, forgot to mention: we were from version 2.0 to 2.1. After upgrading to 2.1, UI often displayed "502 error", and mattermost server crashed.

**Comment by williamwu0220** [comment]
So, this is not a product defect? Looks like I misunderstood? Since we upgraded from clean 2.0 env to 2.1... I'll try it again, thanks.

**Comment by williamwu0220** [comment]
Solved, thanks.
