### ISSUE TITLE
fresh install of mattermost doesn't pass tests

### ISSUE THREAD

**Issue by danoctavian** [mattermost/platform#2653]
I clone the repo.
I run make which sets up the docker container.
It seems to be an issue with defining a dockerhost. How do i solve this problem? Thanks.
```
Failed to ping db err:dial tcp: lookup dockerhost: no such host
--- FAIL: TestGetLogs (1.09s)
panic: Failed to open sql connection dial tcp: lookup dockerhost: no such host [recovered]
	panic: Failed to open sql connection dial tcp: lookup dockerhost: no such host

goroutine 7 [running]:
testing.tRunner.func1(0xc820089680)
	/usr/local/go/src/testing/testing.go:450 +0x171
github.com/mattermost/platform/store.setupConnection(0x97cba8, 0x6, 0xc820157020, 0x5, 0xc820017450, 0x48, 0xa, 0xa, 0x4800, 0xc8201f60b8)
	/Users/dan/repos/gows/src/github.com/mattermost/platform/store/sql_store.go:173 +0x894
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/Users/dan/repos/gows/src/github.com/mattermost/platform/store/sql_store.go:62 +0x120
github.com/mattermost/platform/api.NewServer()
	/Users/dan/repos/gows/src/github.com/mattermost/platform/api/server.go:35 +0xe8
github.com/mattermost/platform/api.Setup()
	/Users/dan/repos/gows/src/github.com/mattermost/platform/api/api_test.go:19 +0x5e
github.com/mattermost/platform/api.TestGetLogs(0xc820089680)
	/Users/dan/repos/gows/src/github.com/mattermost/platform/api/admin_test.go:14 +0x39
testing.tRunner(0xc820089680, 0xd806c0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xb00db8, 0xd806c0, 0x77, 0x77, 0xc8200ddb01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820581ee8, 0xc8200ddb06)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/mattermost/platform/api/_test/_testmain.go:330 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc8201fa000, 0x1b744b8, 0xc820034010)
	/Users/dan/repos/gows/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:33 +0x69
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/Users/dan/repos/gows/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5

goroutine 19 [select]:
github.com/alecthomas/log4go.NewFileLogWriter.func1(0xc820206000)
	/Users/dan/repos/gows/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:87 +0xabc
created by github.com/alecthomas/log4go.NewFileLogWriter
	/Users/dan/repos/gows/src/github.com/mattermost/platform/Godeps/_workspace/src/github.com/alecthomas/log4go/filelog.go:119 +0x38b

goroutine 287 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8200988c0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336
exit status 2
FAIL	github.com/mattermost/platform/api	1.109s

```

**Comment by danoctavian** [comment]
do 

echo $DOCKER_HOST

take the resulting ip (eg. 192.168.99.100)

and paste it at the end of your /etc/hosts as such:

192.168.99.100 dockerhost

this step should be contained in the make file. there is a setup for osx step but it olny pastes "dockerhost" at the end of the /etc/hosts file so it doesn't work.

**Comment by crspeller** [comment]
The process for setting up a development machine is documented here: http://docs.mattermost.com/developer/developer-setup.html

**Comment by danoctavian** [comment]
cheers, did no end up on that page before.
