### ISSUE TITLE
Duplicating messages with retry button

### ISSUE THREAD

**Issue by samogot** [mattermost/platform#2925]
When i write to Town Hall channel, all my messages are duplicatad at the bottom. It looks like they was not sended (and system propse me to retry them). But they was, and other can see them
![image](https://cloud.githubusercontent.com/assets/11226228/15093475/18796642-1492-11e6-8113-0362ba86edc6.png)

**Comment by it33** [comment]
@samogot could you please add repro steps? http://www.mattermost.org/filing-issues/

**Comment by samogot** [comment]
@it33, I think there is no common reproduction steaps, as I think it is related to our server configuration or network problems. I've add some extra `console.log`s , and get this:
```
storePendingPost Object {
	channel_id: "3efzheu1sfr3udafiugcas6kra"
	create_at: 1463657566383
	filenames: Array[0]
	message: "test"
	parent_id: undefined
	pending_post_id: "jsny6preopr5mmetprhefwq7fo:1463657566383"
	state: "failed"
	user_id: "jsny6preopr5mmetprhefwq7fo
}
getPendingPosts 3efzheu1sfr3udafiugcas6kra
POST https://mm.ruranobe.ru/api/v3/teams/xm8rjz3yd7bi8ku9uconpex3xo/channels/3efzheu1sfr3udafiugcas6kra/posts/create 502
method=createPost status=502 statusCode=undefined err=Error: Unsuccessful HTTP response
Object {message: "We received an unexpected status code from the server. (502)"}
updatePendingPost Object {
	channel_id: "3efzheu1sfr3udafiugcas6kra"
	create_at: 1463657566383
	filenames: Array[0]
	message: "test"
	parent_id: undefined
	pending_post_id: "jsny6preopr5mmetprhefwq7fo:1463657566383"
	state: "failed"
	user_id: "jsny6preopr5mmetprhefwq7fo"
}
getPendingPosts 3efzheu1sfr3udafiugcas6kra
websocket closed
websocket re-established connection
storePosts 3efzheu1sfr3udafiugcas6kra Object {
	order: Array[
		0: "1yderyoozbryxeg96ndd77658o"
		1: "szzr7kauj3yjdgmruz5an3p3ew"
		2: "xq8e7tjcr7gkxjqgmrn946e3qw"
		3: "446xp6r5k7r6frpih8ijarx4sc"
		...
	]
	posts: Object{
		1jahrmc44tgczchceu5y5343mh: Object
		1yderyoozbryxeg96ndd77658o: Object {
			channel_id: "3efzheu1sfr3udafiugcas6kra"
			create_at: 1463657566561
			delete_at: 0
			filenames: Array[0]
			hashtags: ""
			id: "1yderyoozbryxeg96ndd77658o"
			message: "test"
			original_id: ""
			parent_id: ""
			pending_post_id: ""
			props: Object
			root_id: ""
			type: ""
			update_at: 1463657566561
			user_id: "jsny6preopr5mmetprhefwq7fo"
		}
		3wjxy66pbjfmzfm5hokssdznpc: Object
		...
	}
}
```

as i understand we've got unexpected disconnect from server while creating post, which cause 502 response and closing websocket. but post is still saved on server. after re-establishing websocket we've get all posts, including the new one, but we haven't any information about connection between latest post returned from server and pending one, wich isn't necessary any more

**Comment by samogot** [comment]
here is server log. MM is just crash on every message into town hall or off-topic. other channels are ok
```
май 25 10:43:53 bablocloud-core platform[2540]: [2016/05/25 10:43:53 MSK] [DEBG] /api/v3/teams/xm8rjz3yd7bi8ku9uconpex3xo/channels/3efzheu1sfr3udafiugcas6kra/posts/create
май 25 10:43:53 bablocloud-core systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
май 25 10:43:53 bablocloud-core systemd[1]: mattermost.service: Unit entered failed state.
май 25 10:43:53 bablocloud-core systemd[1]: mattermost.service: Failed with result 'exit-code'.
май 25 10:43:54 bablocloud-core systemd[1]: mattermost.service: Service hold-off time over, scheduling restart.
май 25 10:43:54 bablocloud-core systemd[1]: Stopped Mattermost Chat Server.
май 25 10:43:54 bablocloud-core systemd[1]: Started Mattermost Chat Server.
май 25 10:43:54 bablocloud-core platform[5234]: [10:43:54 MSK 2016/05/25] [EROR] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:42) Failed to load system translations for 'en' attempting to fall back to 'en'
май 25 10:43:54 bablocloud-core platform[5234]: [10:43:54 MSK 2016/05/25] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/usr/share/webapps/mattermost/i18n/en.json'
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Current version is 3.0.0 (//)
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Enterprise Enabled:
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Current working directory is /usr/share/webapps/mattermost
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Loaded config file from /usr/share/webapps/mattermost/config/config.json
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Server is initializing...
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Pinging sql master database
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Pinging sql replica-0 database
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Deleting any unused pre-release features
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing user api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing team api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing channel api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing post api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing web socket api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing file api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing command api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing admin api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing oauth api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing webhook api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing preference api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing license api routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Parsing server templates at /usr/share/webapps/mattermost/templates/
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Initializing web routes
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [DEBG] Using client directory at /usr/share/webapps/mattermost/webapp/dist/
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Starting Server...
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] Server is listening on 127.0.0.1:8065
май 25 10:43:54 bablocloud-core platform[5234]: [2016/05/25 10:43:54 MSK] [INFO] RateLimiter is enabled
```

**Comment by it33** [comment]
Thanks @samogot appreciate the report, it [looks like someone else is seeing this issue as well](https://github.com/mattermost/platform/issues/3114), we're still trying to find a way to repro it...

**Comment by samogot** [comment]
@it33 i've fixed that. we have build mm in debug mode and get this NPE
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xd8 pc=0x5ec8ac]

goroutine 399 [running]:
panic(0xca10c0, 0xc82000a0d0)
    /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/mattermost/platform/api.sendNotifications(0xc82004b7a0, 0xc82059c1c0, 0xc8202d66e0, 0xc82036b760, 0xc82071d960, 0xc820870000, 0x22, 0x40)
    /home/samogot/builds/mattermost/src/src/github.com/mattermost/platform/api/post.go:520 +0x67ec
created by github.com/mattermost/platform/api.handlePostEventsAndForget.func1
    /home/samogot/builds/mattermost/src/src/github.com/mattermost/platform/api/post.go:281 +0x121d
```

the reason was in a fact that there are 28 users in a team, but 34 userIDs in a channels. that's why problem was reproducing only in town hall and off-topic channel. this database was migrating all way from 1.0 and we recreate team once, so i think problem was in some of migration or team removing scripts
