### ISSUE TITLE
Mattermost will not start up after config change

### ISSUE THREAD

**Issue by TheNixNinja** [mattermost/platform#3369]
#### Summary
Mattermost does not start up after changing max file size

#### Steps to reproduce
 1. Stop a running instance of mattermost ```sudo /etc/init.d/mattermost stop```
 2. Edit config.json change the max file size setting from 52428800 to 10485760
 3. Start the mattermost service ```sudo /etc/init.d/mattermost start```

#### Expected behavior
Expected the server to start up as it was running fine before

#### Observed behavior
To get an error message I had to run the platform executable as root otherwise it just fails start and doesn't report any problems.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: interface conversion: interface is runtime.errorString, not string
[signal 0xb code=0x1 addr=0x0 pc=0x780b9d]

goroutine 1 [running]:
panic(0xcd1aa0, 0xc820262480)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.doLoadConfig.func1(0xc820255d38)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:73 +0x6f
panic(0xccbec0, 0xc82000a0c0)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/mattermost/platform/utils.TestConnection(0xc82007ab00)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/mail.go:89 +0x32d
github.com/mattermost/platform/utils.LoadConfig(0xc820139aa0, 0x22)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/config.go:181 +0x10aa
main.doLoadConfig(0xdce990, 0xb, 0x0, 0x0)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:76 +0x6a
main.main()
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:84 +0x43
```

#### Possible fixes
I have tried putting the setting back to the way it was, and even deleting the config line completely but neither seem to help.

**Comment by TheNixNinja** [comment]
Was also able to find the error message in syslog
```
Jun 17 17:38:52  systemd[1]: Started Mattermost is an open source, self-hosted Slack-alternative.
Jun 17 17:38:52  platform[1965]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Jun 17 17:38:52  platform[1965]: #011panic: interface conversion: interface is runtime.errorString, not string
Jun 17 17:38:52  platform[1965]: [signal 0xb code=0x1 addr=0x0 pc=0x780b9d]
Jun 17 17:38:52  platform[1965]: goroutine 1 [running]:
Jun 17 17:38:52  platform[1965]: panic(0xcd1aa0, 0xc82024a7c0)
Jun 17 17:38:52  platform[1965]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
Jun 17 17:38:52  platform[1965]: main.doLoadConfig.func1(0xc820241d38)
Jun 17 17:38:52  platform[1965]: #011/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:73 +0x6f
Jun 17 17:38:52  platform[1965]: panic(0xccbec0, 0xc82000a0a0)
Jun 17 17:38:52  platform[1965]: #011/usr/local/go/src/runtime/panic.go:443 +0x4e9
Jun 17 17:38:52  platform[1965]: github.com/mattermost/platform/utils.TestConnection(0xc820078b00)
Jun 17 17:38:52  platform[1965]: #011/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/mail.go:89 +0x32d
Jun 17 17:38:52  platform[1965]: github.com/mattermost/platform/utils.LoadConfig(0xc820133a70, 0x22)
Jun 17 17:38:52  platform[1965]: #011/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/utils/config.go:181 +0x10aa
Jun 17 17:38:52  platform[1965]: main.doLoadConfig(0xdce990, 0xb, 0x0, 0x0)
Jun 17 17:38:52  platform[1965]: #011/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:76 +0x6a
Jun 17 17:38:52  platform[1965]: main.main()
Jun 17 17:38:52  platform[1965]: #011/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:84 +0x43
Jun 17 17:38:52  systemd[1]: mattermost.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 17 17:38:52 systemd[1]: mattermost.service: Unit entered failed state.
Jun 17 17:38:52 systemd[1]: mattermost.service: Failed with result 'exit-code'.
```

**Comment by TheNixNinja** [comment]
Dumb User Error 

If anyone runs into this problem check the following
1. That Mattermost server can login to the email account provided
2. That your database server is running.
