### ISSUE TITLE
Incoming webhook json with float64 value panics

### ISSUE THREAD

**Issue by anchepiece** [mattermost/platform#4444]
#### Summary
Incoming webhook json with float64 value unexpectedly panics, returning empty error 500 to client. 

#### Steps to reproduce
platform 3.4.0, master built from source
Start server, create an incoming webhook
Post a json message with attachments having numeric value.
```
curl -X POST -H 'Content-type: application/json' \
    --data '{"text":"A test message!","attachments":[{"color":"#7CD197","fields":[{"title":"Test string","value":"All ok!","short":true}, {"title":"Test float64","value":99,"short":true}]}]}' \
  http://localhost:8065/hooks/mwcbb14537rczyu4ogkoccstuw
```

#### Expected behavior
Expected numeric value to be simply interpreted as string.

#### Observed behavior
platform panics, returning **empty** 500 internal server error **instead** of something like this json formatted 500 error:
{"id":"web.incoming_webhook.parse.app_error","message":"Unable to parse incoming data","detailed_error":"","request_id":"ryyftn9pzjnutj8fr6jx368xay","status_code":500}

Relevant debug log: 
```
2016/11/03 20:27:57 interface conversion: interface is float64, not string
[2016/11/03 20:27:57 EDT] [DEBG] /hooks/mwcbb14537rczyu4ogkoccstuw
[2016/11/03 20:27:57 EDT] [DEBG] Incoming webhook received. Content={"text":"A nice message!","attachments":[{"color":"#7CD197","fields":[{"title":"TestNil","value":null,"short":true}, {"title":"TestFloat64","value":99,"short":true}]}]}
goroutine 1203 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/lib/go-1.6/src/runtime/debug/stack.go:16 +0x18
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x7f716d9dc2b8, 0xc820cb6008, 0x0, 0x1, 0xe21ae0, 0xc82138a3c0)
	/home/dev/go/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:84 +0xb8
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x7f716dab7f40, 0xc8209f6820, 0x7f716d9dc2b8, 0xc820cb6008, 0x0, 0x2ffd601)
	/home/dev/go/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:69 +0x9b
panic(0xe21ae0, 0xc82138a3c0)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/mattermost/platform/model.expandAnnouncements(0xc820cce000)
	/home/dev/go/src/github.com/mattermost/platform/model/incoming_webhook.go:242 +0x9af
github.com/mattermost/platform/model.IncomingWebhookRequestFromJson(0x7f716da9e408, 0xc820996870, 0xc82063c390)
	/home/dev/go/src/github.com/mattermost/platform/model/incoming_webhook.go:265 +0x186
github.com/mattermost/platform/api.incomingWebhook(0xc820ad4900, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/home/dev/go/src/github.com/mattermost/platform/api/webhook.go:380 +0x894
github.com/mattermost/platform/api.handler.ServeHTTP(0x10fb980, 0x10000, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/home/dev/go/src/github.com/mattermost/platform/api/context.go:213 +0x11fc
github.com/mattermost/platform/api.(*handler).ServeHTTP(0xc820bffe60, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	<autogenerated>:1 +0xb6
github.com/mattermost/platform/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8204e44b0, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/home/dev/go/src/github.com/mattermost/platform/vendor/github.com/gorilla/mux/mux.go:103 +0x270
github.com/mattermost/platform/api.(*CorsWrapper).ServeHTTP(0xc820cb6008, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/home/dev/go/src/github.com/mattermost/platform/api/context.go:263 +0x331
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x7f716d9dc2b8, 0xc820cb6008, 0x0, 0x1, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/home/dev/go/src/github.com/mattermost/platform/vendor/github.com/gorilla/handlers/recovery.go:73 +0xb4
github.com/mattermost/platform/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP(0xc820c46080, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	<autogenerated>:52 +0xb4
net/http.serverHandler.ServeHTTP(0xc820d2c180, 0x7f716dab7f40, 0xc8209f6820, 0xc8212c61c0)
	/usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820c9a400)
	/usr/lib/go-1.6/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/lib/go-1.6/src/net/http/server.go:2137 +0x44e
```

#### Possible fixes
incoming_webhook.go : You could do a type assertion and break on it like this:
```
if value, ok := f["value"].(string); ok {
    f["value"] = expandAnnouncement(value)
} else {
    f["value"] = expandAnnouncement(fmt.Sprintf("%v", f["value"]))
}
```
or just skip the type assertion and Sprintf any sent value and use that.

Referencing #3666, #4000, I was unable to find or create an issue on the atlassian issue tracker.

**Comment by jasonblais** [comment]
Closed via #4444, thanks @anchepiece!
