### ISSUE TITLE
Cannot load channel messages, Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by nickolasclarke** [mattermost/platform#4801]
#### Summary
Cannot load channel messages due to `Uncaught TypeError: Cannot read property 'substring' of undefined`
#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
1. Go to https://pre-release.mattermost.com
2. try to load a channel, notice red error banner that asks you to check console.
3. 
#### Observed behavior
```
websocket connecting to wss://pre-release.mattermost.com:443/api/v3/users/websocket
user_profile.jsx:185
Uncaught TypeError: Cannot read property 'substring' of undefined
    at n.value (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:15:25470)
    at u._renderValidatedComponentWithoutOwnerOrContext (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:22650)
    at u._renderValidatedComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:22777)
    at u.performInitialMount (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:18596)
    at u.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:17642)
    at Object.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:11:15795)
    at h.mountChildren (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:57:16304)
    at h._createInitialChildren (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:31189)
    at h.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:29341)
    at Object.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:11:15795)


Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
    at n.value (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:15:25470)
    at u._renderValidatedComponentWithoutOwnerOrContext (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:22650)
    at u._renderValidatedComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:22777)
    at u.performInitialMount (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:18596)
    at u.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:17642)
    at Object.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:11:15795)
    at h.mountChildren (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:57:16304)
    at h._createInitialChildren (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:31189)
    at h.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:56:29341)
    at Object.mountComponent (https://pre-release.mattermost.com/static/main.b74129560ca47dbd2fb0.js:11:15795)
```

#### Possible fixes

```javascript
user_profile.jsx:185:        
 const position = this.props.user.position.substring(0, Constants.MAX_POSITION_LENGTH);
```

**Comment by grundleborg** [comment]
Thanks very much for reporting this bug. It should be fixed by this PR https://github.com/mattermost/platform/pull/4802 which has just been merged and will be running on pre-release.mattermost.com soon.

**Comment by grundleborg** [comment]
This is now fixed.

**Comment by nickolasclarke** [comment]
@grundleborg of course. Glad to see it!
