### ISSUE TITLE
invalid memory address or nil pointer dereference when deactivating user

### ISSUE THREAD

**Issue by iGEL** [mattermost/platform#5696]
#### Summary

invalid memory address or nil pointer dereference when deactivating user

#### Steps to reproduce

I'm using Mattermost 3.6.2 (same thing with 3.6.0, which I had yesterday) with docker (from your repo, [just tiny changes](https://github.com/mattermost/mattermost-docker/compare/3.6.2...BillFront:master)) and MySQL. With `docker run`, I execute this command
```sh
/mattermost/bin/platform user deactivate lucio
```

`lucio` is the name of the user I see in the UI. I already removed him from the only team we have, but I still want to deactivate the entire account.

#### Expected behavior

Some success message, that the user is deactivated

#### Observed behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x419fc8]

goroutine 1 [running]:
panic(0xbde860, 0xc42001e060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.getUserFromUserArg(0x7ffd477db9e6, 0x5, 0x1)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/userargs.go:21 +0x28
main.getUsersFromUserArgs(0xc4200f2a50, 0x1, 0x1, 0xb, 0x6, 0xc9080d)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/userargs.go:13 +0xa2
main.changeUsersActiveStatus(0xc4200f2a50, 0x1, 0x1, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/user.go:162 +0x43
main.userDeactivateCmdF(0x106c1a0, 0xc4200f2a50, 0x1, 0x1, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/user.go:189 +0xc9
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).execute(0x106c1a0, 0xc4200f29e0, 0x1, 0x1, 0x106c1a0, 0xc4200f29e0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:632 +0x23e
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42000eb40, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/mattermost/platform/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42000eb40, 0xc4200f2740, 0xb)
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
	/var/lib/jenkins/jobs/msr/jobs/platform-release/workspace/src/github.com/mattermost/platform/cmd/platform/mattermost.go:50 +0x49f
```
with exit code 2

**Comment by iGEL** [comment]
On a side note, it would be really nice to be able to see the status of the user. I imagine something like this:
```sh
platform user status lucio
```
Besides activation status, it could provide other info like team memberships, email address etc.

**Comment by jasonblais** [comment]
Hey @iGEL, terribly sorry for the late response.

Were  you able to resolve the issue? I think the CLI command might be missing something but I'm not too familiar with Docker setups.

Does invoking `platform help` work?

**Comment by lindy65** [comment]
Closing this issue due to inactivity. Please reopen if the issue is still unresolved.
