### ISSUE TITLE
Error "database schema ... cannot be upgraded" when executing "make run"

### ISSUE THREAD

**Issue by apaatsio** [mattermost/platform#892]
I'm trying to execute `make run` but I'm getting error "The database schema version of 0.8.0 cannot be upgraded.  You must not skip a version."

I wonder what I skipped and how can I not skip.

```
[10/01/15 17:04:40] [INFO] Current version is 1.0.0 (dev/Thu Oct  1 14:04:02 UTC 2015/be300b7e7db41658576604c0594f368427b5de2b)
[10/01/15 17:04:40] [INFO] Current working directory is /home/antti/go/src/github.com/mattermost/platform
[10/01/15 17:04:40] [INFO] Loaded config file from /home/antti/go/src/github.com/mattermost/platform/config/config.json
[10/01/15 17:04:40] [INFO] Server is initializing...
[10/01/15 17:04:40] [INFO] Pinging sql master database
[10/01/15 17:04:40] [INFO] Pinging sql replica-0 database
[10/01/15 17:04:40] [CRIT] The database schema version of 0.8.0 cannot be upgraded.  You must not skip a version.
panic: The database schema version of 0.8.0 cannot be upgraded.  You must not skip a version.

goroutine 1 [running]:
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/home/antti/go/src/github.com/mattermost/platform/store/sql_store.go:82 +0x1586
github.com/mattermost/platform/api.NewServer()
	/home/antti/go/src/github.com/mattermost/platform/api/server.go:33 +0x15a
main.main()
	/home/antti/go/src/github.com/mattermost/platform/mattermost.go:50 +0x4d8

...

goroutine 9 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208033680)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
godep: go exit status 1
```

**Comment by coreyhulen** [comment]
We've bumped the version to 1.0  Since you are working from master you have caught an interim 0.8.0 version.  You can delete the row Version=0.8.0 in the mattermost Systems table (or set it to 0.7.0).

**Comment by it33** [comment]
Hi @apaatsio, please let us know if this works?

**Comment by apaatsio** [comment]
Yes, deleting the Version 0.8.0 row from Systems table worked. Thanks!
