### ISSUE TITLE
Compliation in ARM - JS error

### ISSUE THREAD

**Issue by hi-t-ch** [mattermost/platform#918]
Hi everyone,
I'm trying to compile mattermost in ARM plateform, but it turns out that I got this error during the process (using make).
```bash
Checking for style guide compliance
cd web/react && node_modules/eslint/bin/eslint.js --quiet components/* dispatcher/* pages/* stores/* utils/*

/root/platform/web/react/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.')
                              ^
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (/root/platform/web/react/node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (/root/platform/web/react/node_modules/eslint/lib/eslint.js:808:24)
    at processText (/root/platform/web/react/node_modules/eslint/lib/cli-engine.js:199:27)
    at processFile (/root/platform/web/react/node_modules/eslint/lib/cli-engine.js:224:12)
    at /root/platform/web/react/node_modules/eslint/lib/cli-engine.js:391:26
    at walk (/root/platform/web/react/node_modules/eslint/lib/util/traverse.js:82:9)
    at /root/platform/web/react/node_modules/eslint/lib/util/traverse.js:104:9
    at Array.forEach (native)
    at traverse (/root/platform/web/react/node_modules/eslint/lib/util/traverse.js:103:11)
    at CLIEngine.executeOnFiles (/root/platform/web/react/node_modules/eslint/lib/cli-engine.js:382:9)
make: *** [travis] Error 8
```
Is it a known issue? Thanks !

**Comment by coreyhulen** [comment]
This appears to be a javascript/npm/eslint issue not specific to Mattermost.  Once the javascript is built into our bundle.js file you don't need the build tools anymore.

You can:
1.  Attempt to get eslint working on ARM.  I would make sure you have the latest version using `sudo npm i -g eslint` `sudo npm i -g eslint-plugin-react`.  You can check your version with `eslint -v`.  Looks like something similar too https://github.com/eslint/eslint/issues/1979
2.  Attempt to cross-compile from a linux (amd64) machine to arm.

**Comment by hi-t-ch** [comment]
Will try that. Thanks for the input! As this issue is not related to Mattermost, closing it.
Cheers \o/

**Comment by ionas** [comment]
Where you able to compile it on arm at all?

**Comment by gamersalpha** [comment]
Hello there, 

i m looking how make a cross compiling for arm raspberry ?
